name: Create containers
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [fedora, debian-x86_64, arch, debian-i386, void]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: "Generate Dockerfile"
        env:
          OS: ${{ matrix.os }}
        run: ./contrib/ci/generate_docker.py
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: fwupd/fwupd/fwupd-${{matrix.os}}:latest
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
